/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MrrLazyImport = createFileRoute('/mrr')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MrrLazyRoute = MrrLazyImport.update({
  id: '/mrr',
  path: '/mrr',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mrr.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/mrr': {
      id: '/mrr'
      path: '/mrr'
      fullPath: '/mrr'
      preLoaderRoute: typeof MrrLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/mrr': typeof MrrLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/mrr': typeof MrrLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/mrr': typeof MrrLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mrr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mrr'
  id: '__root__' | '/' | '/mrr'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MrrLazyRoute: typeof MrrLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MrrLazyRoute: MrrLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mrr"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/mrr": {
      "filePath": "mrr.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
